# Generated by Django 5.2 on 2025-05-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ni',
            field=models.PositiveIntegerField(blank=True, max_length=100, null=True),
        ),
    ]
