# Generated by Django 5.2 on 2025-05-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_usuario_ni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ni',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
