# Generated by Django 5.1.6 on 2025-03-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('ano_publicacao', models.IntegerField()),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Livros',
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
