# Generated by Django 5.1.7 on 2025-03-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=500)),
                ('data_hora', models.DateTimeField()),
                ('local', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=150)),
            ],
        ),
    ]
